// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProfessionalsSiancaValley.Api.Data;

#nullable disable

namespace ProfessionalsSiancaValley.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228042026_AddRoleToUsers")]
    partial class AddRoleToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProfessionalsSiancaValley.Api.Models.Miniature", b =>
                {
                    b.Property<int>("Id_Miniature")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Miniature"));

                    b.Property<bool>("Bloqueado_Por_Sistema")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Dislikes")
                        .HasColumnType("integer");

                    b.Property<string>("Email_Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Es_Contenido_Sensible")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado_Revision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_Publicacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Publicacion")
                        .HasColumnType("integer");

                    b.Property<string>("Id_User")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre_Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo_Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalReportes")
                        .HasColumnType("integer");

                    b.Property<string>("Url_Miniatura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Vistas")
                        .HasColumnType("integer");

                    b.HasKey("Id_Miniature");

                    b.ToTable("Miniatures");
                });

            modelBuilder.Entity("ProfessionalsSiancaValley.Api.Models.Report", b =>
                {
                    b.Property<int>("Id_Report")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Report"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email_Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_Reporte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Miniature")
                        .HasColumnType("integer");

                    b.Property<string>("Id_User")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MiniatureId_Miniature")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre_Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Report");

                    b.HasIndex("Id_Miniature");

                    b.HasIndex("MiniatureId_Miniature");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ProfessionalsSiancaValley.Api.Models.User", b =>
                {
                    b.Property<string>("IdUser")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id_user");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("EstadoEdad")
                        .HasColumnType("boolean")
                        .HasColumnName("estado_edad");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProfessionalAssociationRegistration")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("professional_association_registration");

                    b.Property<string>("ProfessionalLicense")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("professional_license");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialty");

                    b.Property<string>("University")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("university");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserPosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_position");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserPosition"));

                    b.HasKey("IdUser");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ProfessionalsSiancaValley.Api.Models.Report", b =>
                {
                    b.HasOne("ProfessionalsSiancaValley.Api.Models.Miniature", "Miniature")
                        .WithMany()
                        .HasForeignKey("Id_Miniature")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProfessionalsSiancaValley.Api.Models.Miniature", null)
                        .WithMany("Reports")
                        .HasForeignKey("MiniatureId_Miniature");

                    b.Navigation("Miniature");
                });

            modelBuilder.Entity("ProfessionalsSiancaValley.Api.Models.Miniature", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
